# Generated by Django 4.1 on 2024-02-16 02:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("single_pages", "0004_restraunt_url_alter_restraunt_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Restraunt",
            new_name="Restaurant",
        ),
        migrations.RenameModel(
            old_name="RestrauntMenu",
            new_name="RestaurantMenu",
        ),
        migrations.RenameModel(
            old_name="RestrauntReview",
            new_name="RestaurantReview",
        ),
    ]
