# Generated by Django 4.1 on 2024-02-16 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0005_rename_restraunt_restaurant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantmenu",
            old_name="restraunt_pk",
            new_name="Restaurant_pk",
        ),
        migrations.RenameField(
            model_name="restaurantreview",
            old_name="restraunt_pk",
            new_name="Restaurant_pk",
        ),
    ]
