# Generated by Django 5.0.1 on 2024-01-30 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_thumnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="thumnail",
            new_name="thumbnail",
        ),
    ]
