# Generated by Django 4.1 on 2024-02-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                ("completed", models.BooleanField(default=False, verbose_name="완료 여부")),
                ("important", models.BooleanField(default=False, verbose_name="중요 여부")),
            ],
        ),
    ]
